# Generated by Django 4.1 on 2022-08-14 18:19

from django.db import migrations, models
import django.db.models.deletion
import teams.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', teams.fields.CaseInsensitiveCharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='id_birth_cert_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county_name', teams.fields.CaseInsensitiveCharField(max_length=15, unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.county')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.county'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.subcounty'),
        ),
    ]
