# Generated by Django 4.1 on 2022-08-18 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_remove_team_county_name_remove_team_sub_county_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='profile.jpg', upload_to='coach_images')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_No', models.IntegerField(unique=True)),
                ('birth_date', models.DateField()),
                ('caf_level', models.CharField(choices=[('0', 'Beginner'), ('1', 'FUFA level 1'), ('2', 'CAF C Diploma'), ('3', 'CAF B Diploma'), ('4', 'CAF A Diploma')], default=0, max_length=3)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.county')),
                ('sub_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.subcounty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
