# Generated by Django 4.1 on 2022-08-19 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='avatar',
            field=models.ImageField(default='profile.png', upload_to='coach_images'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach', to='teams.coach'),
        ),
    ]
