# Generated by Django 4.1 on 2022-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_coach_avatar_alter_coach_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='caf_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('FUFA level 1', 'FUFA level 1'), ('CAF C Diploma', 'CAF C Diploma'), ('CAF B Diploma', 'CAF B Diploma'), ('CAF A Diploma', 'CAF A Diploma')], default='Beginner', max_length=15),
        ),
    ]
