# Generated by Django 4.1 on 2022-08-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_coach_caf_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='county_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='sub_county_name',
            new_name='name',
        ),
    ]
