# Generated by Django 4.1 on 2022-08-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_rename_county_name_county_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='name',
            new_name='county_name',
        ),
        migrations.RenameField(
            model_name='subcounty',
            old_name='name',
            new_name='sub_county_name',
        ),
    ]
