# Generated by Django 4.1 on 2022-08-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_player_sub_county_alter_team_sub_county_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='coach_name',
            new_name='coach',
        ),
    ]
