# Generated by Django 4.1 on 2022-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_rename_coach_name_team_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='ref',
            options={'verbose_name': 'Referee', 'verbose_name_plural': 'Referees'},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'verbose_name': 'Sub County', 'verbose_name_plural': 'Sub Counties'},
        ),
        migrations.AlterField(
            model_name='coach',
            name='id_No',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_birth_cert_no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ref',
            name='id_No',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
