# Generated by Django 4.1 on 2022-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_alter_coach_options_alter_county_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Team short name'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
    ]
