# Generated by Django 4.1 on 2022-08-24 13:14

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import teams.fields


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_remove_season_league_remove_season_teams_and_more'),
        ('teams', '0014_team_short_name_team_slug'),
        ('league', '0003_alter_player_id_alter_playercustomfields_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', teams.fields.CaseInsensitiveCharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='playercustomfields',
            name='player',
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='max_players',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='season',
            name='registration_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='transfer_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='away_team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='teams', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.team', verbose_name='Away team'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='home_team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='teams', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team', verbose_name='Home team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='standings_order',
            field=models.IntegerField(choices=[(0, 'played, Points, Wins, Lost, Draw, Goals_For, Goals_Aganist,Goal_Diff'), (1, 'played, Wins, Lost, Draw, Goals_For, Goals_Aganist,Goal_Diff, Points')], default=0, verbose_name='Standings order'),
        ),
        migrations.AlterField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.team', verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='team',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='teams', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.team', verbose_name='Team'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerCustomFields',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='League', to='league.league'),
        ),
    ]
