# Generated by Django 4.1 on 2022-08-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_team_short_name_team_slug'),
        ('league', '0006_remove_season_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='away_team_score',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='city',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='home_team_score',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_score', models.IntegerField(blank=True, null=True, verbose_name='Home team score')),
                ('away_team_score', models.IntegerField(blank=True, null=True, verbose_name='Away team score')),
                ('venue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Venue')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teams.team', verbose_name='Away team')),
                ('cente_ref', models.ForeignKey(limit_choices_to={'position': 'CR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CR', to='teams.ref')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teams.team', verbose_name='Home team')),
            ],
        ),
    ]
