# Generated by Django 4.1 on 2022-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_schedule_date_match_assistant_ref_match_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'ordering': ('-points', 'goal_diff', 'goals_for'), 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='standings',
            name='roster_image',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='score',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='score_lost',
        ),
        migrations.AddField(
            model_name='standings',
            name='goal_diff',
            field=models.IntegerField(default=0, null=True, verbose_name='GD'),
        ),
        migrations.AddField(
            model_name='standings',
            name='goals_aganist',
            field=models.IntegerField(default=0, null=True, verbose_name='GA'),
        ),
        migrations.AddField(
            model_name='standings',
            name='goals_for',
            field=models.IntegerField(default=0, null=True, verbose_name='GF'),
        ),
        migrations.AlterField(
            model_name='season',
            name='standings_order',
            field=models.IntegerField(choices=[(0, 'Matches, Points, Wins, Lost, Draw, Goals_For, Goals_Aganist,Goal_Diff'), (1, 'Matches, Wins, Lost, Draw, Goals_For, Goals_Aganist,Goal_Diff, Points')], default=0, verbose_name='Standings order'),
        ),
    ]
