# Generated by Django 4.1 on 2022-08-22 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import teams.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0013_alter_coach_options_alter_county_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', teams.fields.CaseInsensitiveCharField(max_length=100, unique=True)),
                ('chairman', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_chairman', to=settings.AUTH_USER_MODEL)),
                ('county', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.county')),
                ('secretary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_secretary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', teams.fields.CaseInsensitiveCharField(max_length=100, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('chairman', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branch_chairman', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branch_secretary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateTimeField()),
                ('transfer_deadline', models.DateTimeField()),
                ('max_players', models.PositiveIntegerField()),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league', to=settings.AUTH_USER_MODEL)),
                ('teams', smart_selects.db_fields.ChainedManyToManyField(chained_field='branch', chained_model_field='county', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', teams.fields.CaseInsensitiveCharField(max_length=100)),
                ('season', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('sub_branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='branch', chained_model_field='branch', on_delete=django.db.models.deletion.CASCADE, to='teams.subcounty')),
            ],
        ),
    ]
