# Generated by Django 4.1 on 2022-08-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_options_alter_subbranch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='league',
        ),
        migrations.RemoveField(
            model_name='season',
            name='teams',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
